# Generated by Django 5.1.6 on 2025-09-05 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/images/')),
                ('dyslexia_type', models.CharField(choices=[('Developmental', 'Developmental'), ('Acquired', 'Acquired'), ('Phonological', 'Phonological'), ('Surface', 'Surface'), ('Rapid naming deficit', 'Rapid naming deficit'), ('Visual', 'Visual')], default='Developmental', max_length=40)),
                ('prompt', models.CharField(blank=True, default='', max_length=255)),
                ('choice_a', models.CharField(blank=True, default='', max_length=120)),
                ('choice_b', models.CharField(blank=True, default='', max_length=120)),
                ('choice_c', models.CharField(blank=True, default='', max_length=120)),
                ('correct_choice', models.CharField(blank=True, default='', max_length=1)),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(blank=True, default='', max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_ms', models.PositiveIntegerField(default=0)),
                ('tts_plays', models.PositiveIntegerField(default=0)),
                ('repeats', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attempts', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
