# Generated by Django 5.1.2 on 2025-09-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('dyslexia_type', models.CharField(choices=[('Developmental', 'Developmental'), ('Acquired', 'Acquired'), ('Phonological', 'Phonological'), ('Surface', 'Surface'), ('Rapid naming deficit', 'Rapid naming deficit'), ('Visual', 'Visual')], default='Developmental', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.module'),
        ),
    ]
