# Generated by Django 5.1.2 on 2025-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_module_lesson_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyslexiaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Developmental', 'Developmental'), ('Acquired', 'Acquired'), ('Phonological', 'Phonological'), ('Surface', 'Surface'), ('Rapid naming deficit', 'Rapid naming deficit'), ('Visual', 'Visual')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='dyslexia_type',
        ),
        migrations.AddField(
            model_name='module',
            name='dyslexia_types',
            field=models.ManyToManyField(related_name='modules', to='lessons.dyslexiatype'),
        ),
    ]
