# Generated by Django 5.1.6 on 2025-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_childprofile_dyslexia_type_alter_childprofile_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Non-Parent'), ('INDEPENDENT', 'Independent')], default='CHILD', max_length=20),
        ),
    ]
