# Generated by Django 5.1.6 on 2025-09-05 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='dyslexia_type',
            field=models.CharField(choices=[('General', 'General'), ('Phonological', 'Phonological'), ('Visual', 'Visual'), ('Surface', 'Surface'), ('Rapid Naming', 'Rapid Naming'), ('Double Deficit', 'Double Deficit'), ('Other', 'Other')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
