# Generated by Django 5.1.6 on 2025-09-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_childprofile_dyslexia_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='dyslexia_type',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Phonological', 'Phonological'), ('Visual', 'Visual'), ('Surface', 'Surface'), ('Rapid Naming', 'Rapid Naming'), ('Double Deficit', 'Double Deficit'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('INDEPENDENT', 'Independent')], default='CHILD', max_length=20),
        ),
    ]
