# Generated by Django 5.1.6 on 2025-09-30 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_childprofile_dyslexia_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyslexia_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tts_usage_count', models.IntegerField(default=0)),
                ('tts_questions_used', models.JSONField(default=list)),
                ('stt_responses', models.JSONField(default=dict)),
                ('stt_accuracy', models.FloatField(default=0.0)),
                ('response_times', models.JSONField(default=dict)),
                ('completion_time', models.FloatField(default=0.0)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('speech_fluency_metrics', models.JSONField(default=dict)),
                ('error_patterns', models.JSONField(default=list)),
                ('child_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluation_data',
            },
        ),
    ]
